name : pipeline CI

on:
  push:
    branches: ["main"]
  pull_request :
    branches: ["main"]
jobs :
  build :
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps :
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - uses : actions/checkout@v1
      - name : log in to Docker Hub
        uses : docker/login-action@v1
        with :
          username : ${{secrets.USER_NAME}}
          password : ${{secrets.USER_PASSWORD}}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
          
      - name: set API key's env var
        env:
          API_KEY: ${{ secrets.API_KEY }}
      
      
      
      - name : Build the Docker Image
        run : docker build . --file Dockerfile --tag sadok34/tp1cryptoapi:V1.0.0

      - name : Push Docker Image to Docker Hub
        run : docker push ${{secrets.USER_NAME}}/tp1cryptoapi:V1.0.0
